swiftlint_version: 0.61.0

included:
  - Sources
  - Tests
excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData

analyzer_rules:
  - unused_declaration
  - unused_import

disabled_rules:
  - trailing_comma
  - cyclomatic_complexity
  - file_length

opt_in_rules:
  - attributes
  - closure_spacing
  - empty_count
  - explicit_init
  - force_unwrapping
  - literal_expression_end_indentation
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_type_annotation
  - sorted_imports
  - yoda_condition

line_length:
  ignores_comments: true
  ignores_urls: true
  warning: 120
  error: 160

identifier_name:
  min_length: 2
  excluded: [id, x, y, i, j, r, g, b]

function_body_length:
  warning: 80
  error: 120

type_body_length:
  warning: 400
  error: 600

vertical_whitespace:
  max_empty_lines: 2

nesting:
  type_level: 2

colon:
  apply_to_dictionaries: true

trailing_whitespace:
  ignores_empty_lines: false

force_cast: error
force_try: warning
todo: warning

reporter: "xcode"
